services:
  webapp:
    build: .
    image: emby-auto-checkin:latest
    container_name: emby-auto-checkin-webapp
    ports:
      - "5055:5055"
    volumes:
      - ./data:/app/data
    restart: unless-stopped
    depends_on:
      - tg_service
      - scheduler
    environment:
      - TG_SERVICE_HOST=tg_service
      - TG_SERVICE_PORT=5056
      - SCHEDULER_HOST=scheduler
      - SCHEDULER_PORT=5057
    command: gunicorn -w 1 -b 0.0.0.0:5055 'webapp:create_app()'

  scheduler:
    build: .
    image: emby-auto-checkin:latest
    container_name: emby-auto-checkin-scheduler
    ports:
      - "5057:5057"
    volumes:
      - ./data:/app/data
    restart: unless-stopped
    depends_on:
      - tg_service
    environment:
      - TG_SERVICE_HOST=tg_service
      - TG_SERVICE_PORT=5056
    command: gunicorn -w 1 -b 0.0.0.0:5057 'run_scheduler:app'

  tg_service:
    build: .
    image: emby-auto-checkin:latest
    container_name: emby-auto-checkin-tg-service
    ports:
      - "5056:5056"
    volumes:
      - ./data:/app/data
    restart: unless-stopped
    command: uvicorn tg_service.main:app --host 0.0.0.0 --port 5056
